#############################################################################
# Makefile for building: BlankNGL
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  BlankNGL.pro
# Template: app
# Command: /Users/georgie/Qt/5.15.1/clang_64/bin/qmake -o Makefile BlankNGL.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT5BUILD -DGL_SILENCE_DEPRECATION -DQT5BUILD -DFMT_HEADER_ONLY -DUSEGLM -DGLM_ENABLE_EXPERIMENTAL -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -arch x86_64 -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -Wno-unused-parameter -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/usr/local/include -I/public/devel/include -I/Users/georgie/vcpkg/installed/x64-linux/include -I/Users/georgie/NGL/include -I/Users/georgie/NGL/gl3w -I/Users/georgie/Qt/5.15.1/clang_64/lib/QtOpenGL.framework/Headers -I/Users/georgie/Qt/5.15.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers -I/Users/georgie/Qt/5.15.1/clang_64/lib/QtCore.framework/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/georgie/Qt/5.15.1/clang_64/mkspecs/macx-clang -F/Users/georgie/Qt/5.15.1/clang_64/lib
QMAKE         = /Users/georgie/Qt/5.15.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/georgie/Qt/5.15.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/georgie/Qt/5.15.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BlankNGL1.0.0
DISTDIR = /Users/georgie/University/MSc/ASE/Labs/CAVE_ASE/obj/BlankNGL1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@loader_path/L/Users/georgie/NGL/lib -Wl,-rpath,/Users/georgie/NGL/lib -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/georgie/Qt/5.15.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/georgie/Qt/5.15.1/clang_64/lib -L/usr/local/lib -L/Users/georgie/vcpkg/installed/x64-linux/lib -L/Users/georgie/NGL/lib -l NGL -framework QtOpenGL -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/NGLScene.cpp \
		src/NGLSceneMouseControls.cpp 
OBJECTS       = obj/main.o \
		obj/NGLScene.o \
		obj/NGLSceneMouseControls.o
DIST          = .qmake.stash \
		BlankNGL.pro include/NGLScene.h \
		include/WindowParams.h src/main.cpp \
		src/NGLScene.cpp \
		src/NGLSceneMouseControls.cpp
QMAKE_TARGET  = BlankNGL
DESTDIR       = 
TARGET        = BlankNGL

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx10.15
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/georgie/University/MSc/ASE/Labs/CAVE_ASE/BlankNGL.pro


include /Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

BlankNGL:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BlankNGL.pro .qmake.cache /Users/georgie/Qt/5.15.1/clang_64/mkspecs/macx-clang/qmake.conf /Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/qdevice.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/device_config.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/unix.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/mac.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/macx.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/clang.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/qconfig.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/georgie/NGL/UseNGL.pri \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/default_post.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qml_debug.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/mac.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qt.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/resources_functions.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/resources.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/moc.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/uic.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/yacc.prf \
		/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/lex.prf \
		BlankNGL.pro \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile BlankNGL.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/spec_pre.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/qdevice.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/device_config.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/unix.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/mac.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/macx.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/sanitize.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/gcc-base.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/clang.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/common/clang-mac.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/qconfig.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qt_functions.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qt_config.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/toolchain.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/default_pre.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/georgie/NGL/UseNGL.pri:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/resolve_config.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/default_post.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qml_debug.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/mac.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/warn_on.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qt.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/resources_functions.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/resources.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/moc.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/unix/opengl.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/uic.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/unix/thread.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/qmake_use.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/file_copies.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/rez.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/exceptions.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/yacc.prf:
/Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/lex.prf:
BlankNGL.pro:
/Users/georgie/Qt/5.15.1/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
/Users/georgie/Qt/5.15.1/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
/Users/georgie/Qt/5.15.1/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BlankNGL.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile BlankNGL

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/NGLScene.h include/WindowParams.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/NGLScene.cpp src/NGLSceneMouseControls.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -arch x86_64 -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -Wno-unused-parameter -dM -E -o moc/moc_predefs.h /Users/georgie/Qt/5.15.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

obj/main.o: src/main.cpp /usr/local/include/QtGui/QGuiApplication \
		/usr/local/include/QtGui/qguiapplication.h \
		/usr/local/include/QtGui/qtguiglobal.h \
		/usr/local/include/QtCore/qglobal.h \
		/usr/local/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/QtCore/qconfig.h \
		/usr/local/include/QtCore/qtcore-config.h \
		/usr/local/include/QtCore/qsystemdetection.h \
		/usr/local/include/QtCore/qprocessordetection.h \
		/usr/local/include/QtCore/qcompilerdetection.h \
		/usr/local/include/QtCore/qtypeinfo.h \
		/usr/local/include/QtCore/qsysinfo.h \
		/usr/local/include/QtCore/qlogging.h \
		/usr/local/include/QtCore/qflags.h \
		/usr/local/include/QtCore/qatomic.h \
		/usr/local/include/QtCore/qbasicatomic.h \
		/usr/local/include/QtCore/qatomic_bootstrap.h \
		/usr/local/include/QtCore/qgenericatomic.h \
		/usr/local/include/QtCore/qatomic_cxx11.h \
		/usr/local/include/QtCore/qatomic_msvc.h \
		/usr/local/include/QtCore/qglobalstatic.h \
		/usr/local/include/QtCore/qmutex.h \
		/usr/local/include/QtCore/qnumeric.h \
		/usr/local/include/QtCore/qversiontagging.h \
		/usr/local/include/QtGui/qtgui-config.h \
		/usr/local/include/QtCore/qcoreapplication.h \
		/usr/local/include/QtCore/qstring.h \
		/usr/local/include/QtCore/qchar.h \
		/usr/local/include/QtCore/qbytearray.h \
		/usr/local/include/QtCore/qrefcount.h \
		/usr/local/include/QtCore/qnamespace.h \
		/usr/local/include/QtCore/qarraydata.h \
		/usr/local/include/QtCore/qstringliteral.h \
		/usr/local/include/QtCore/qstringalgorithms.h \
		/usr/local/include/QtCore/qstringview.h \
		/usr/local/include/QtCore/qstringbuilder.h \
		/usr/local/include/QtCore/qobject.h \
		/usr/local/include/QtCore/qobjectdefs.h \
		/usr/local/include/QtCore/qobjectdefs_impl.h \
		/usr/local/include/QtCore/qlist.h \
		/usr/local/include/QtCore/qalgorithms.h \
		/usr/local/include/QtCore/qiterator.h \
		/usr/local/include/QtCore/qhashfunctions.h \
		/usr/local/include/QtCore/qpair.h \
		/usr/local/include/QtCore/qvector.h \
		/usr/local/include/QtCore/qcontainertools_impl.h \
		/usr/local/include/QtCore/qpoint.h \
		/usr/local/include/QtCore/qbytearraylist.h \
		/usr/local/include/QtCore/qstringlist.h \
		/usr/local/include/QtCore/qregexp.h \
		/usr/local/include/QtCore/qstringmatcher.h \
		/usr/local/include/QtCore/qcoreevent.h \
		/usr/local/include/QtCore/qscopedpointer.h \
		/usr/local/include/QtCore/qmetatype.h \
		/usr/local/include/QtCore/qvarlengtharray.h \
		/usr/local/include/QtCore/qcontainerfwd.h \
		/usr/local/include/QtCore/qobject_impl.h \
		/usr/local/include/QtCore/qeventloop.h \
		/usr/local/include/QtGui/qwindowdefs.h \
		/usr/local/include/QtGui/qwindowdefs_win.h \
		/usr/local/include/QtGui/qinputmethod.h \
		/usr/local/include/QtCore/qlocale.h \
		/usr/local/include/QtCore/qvariant.h \
		/usr/local/include/QtCore/qmap.h \
		/usr/local/include/QtCore/qdebug.h \
		/usr/local/include/QtCore/qhash.h \
		/usr/local/include/QtCore/qtextstream.h \
		/usr/local/include/QtCore/qiodevice.h \
		/usr/local/include/QtCore/qset.h \
		/usr/local/include/QtCore/qcontiguouscache.h \
		/usr/local/include/QtCore/qsharedpointer.h \
		/usr/local/include/QtCore/qshareddata.h \
		/usr/local/include/QtCore/qsharedpointer_impl.h \
		/usr/local/include/QtCore/qsize.h \
		/usr/local/include/QtCore/qmargins.h \
		include/NGLScene.h \
		/Users/georgie/NGL/include/ngl/Vec3.h \
		/Users/georgie/NGL/include/ngl/Types.h \
		/Users/georgie/NGL/gl3w/gl3w.h \
		/Users/georgie/NGL/gl3w/glcorearb.h \
		/Users/georgie/NGL/include/ngl/fmt/format.h \
		/Users/georgie/NGL/include/ngl/fmt/format.cc \
		/Users/georgie/NGL/include/ngl/NGLMessage.h \
		/Users/georgie/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/ext/vector_bool3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/qualifier.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/simd/platform.h \
		/usr/local/include/glm/simd/neon.h \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/detail/compute_vector_relational.hpp \
		/usr/local/include/glm/ext/vector_bool3_precision.hpp \
		/usr/local/include/glm/ext/vector_float3.hpp \
		/usr/local/include/glm/ext/vector_float3_precision.hpp \
		/usr/local/include/glm/ext/vector_double3.hpp \
		/usr/local/include/glm/ext/vector_double3_precision.hpp \
		/usr/local/include/glm/ext/vector_int3.hpp \
		/usr/local/include/glm/ext/vector_int3_sized.hpp \
		/usr/local/include/glm/ext/scalar_int_sized.hpp \
		/usr/local/include/glm/ext/vector_uint3.hpp \
		/usr/local/include/glm/ext/vector_uint3_sized.hpp \
		/usr/local/include/glm/ext/scalar_uint_sized.hpp \
		include/WindowParams.h \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		/usr/local/include/QtGui/QPaintDeviceWindow \
		/usr/local/include/QtGui/qpaintdevicewindow.h \
		/usr/local/include/QtGui/QWindow \
		/usr/local/include/QtGui/qwindow.h \
		/usr/local/include/QtCore/QObject \
		/usr/local/include/QtCore/QEvent \
		/usr/local/include/QtCore/QMargins \
		/usr/local/include/QtCore/QRect \
		/usr/local/include/QtCore/qrect.h \
		/usr/local/include/QtGui/qsurface.h \
		/usr/local/include/QtGui/qsurfaceformat.h \
		/usr/local/include/QtGui/qicon.h \
		/usr/local/include/QtGui/qpixmap.h \
		/usr/local/include/QtGui/qpaintdevice.h \
		/usr/local/include/QtGui/qcolor.h \
		/usr/local/include/QtGui/qrgb.h \
		/usr/local/include/QtGui/qrgba64.h \
		/usr/local/include/QtGui/qimage.h \
		/usr/local/include/QtGui/qpixelformat.h \
		/usr/local/include/QtGui/qtransform.h \
		/usr/local/include/QtGui/qmatrix.h \
		/usr/local/include/QtGui/qpolygon.h \
		/usr/local/include/QtGui/qregion.h \
		/usr/local/include/QtCore/qdatastream.h \
		/usr/local/include/QtCore/qline.h \
		/usr/local/include/QtGui/qcursor.h \
		/usr/local/include/QtGui/QPaintDevice \
		/usr/local/include/QtGui/QOpenGLContext \
		/usr/local/include/QtGui/qopenglcontext.h \
		/usr/local/include/QtCore/QScopedPointer \
		/usr/local/include/QtGui/QSurfaceFormat \
		/usr/local/include/QtGui/qopengl.h \
		/usr/local/include/QtCore/qt_windows.h \
		/usr/local/include/QtGui/qopengles2ext.h \
		/usr/local/include/QtGui/qopenglext.h \
		/usr/local/include/QtGui/qopenglversionfunctions.h \
		/usr/local/include/QtGui/QImage
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/NGLScene.o: src/NGLScene.cpp /Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/include/QtGui/qtguiglobal.h \
		/usr/local/include/QtCore/qglobal.h \
		/usr/local/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/QtCore/qconfig.h \
		/usr/local/include/QtCore/qtcore-config.h \
		/usr/local/include/QtCore/qsystemdetection.h \
		/usr/local/include/QtCore/qprocessordetection.h \
		/usr/local/include/QtCore/qcompilerdetection.h \
		/usr/local/include/QtCore/qtypeinfo.h \
		/usr/local/include/QtCore/qsysinfo.h \
		/usr/local/include/QtCore/qlogging.h \
		/usr/local/include/QtCore/qflags.h \
		/usr/local/include/QtCore/qatomic.h \
		/usr/local/include/QtCore/qbasicatomic.h \
		/usr/local/include/QtCore/qatomic_bootstrap.h \
		/usr/local/include/QtCore/qgenericatomic.h \
		/usr/local/include/QtCore/qatomic_cxx11.h \
		/usr/local/include/QtCore/qatomic_msvc.h \
		/usr/local/include/QtCore/qglobalstatic.h \
		/usr/local/include/QtCore/qmutex.h \
		/usr/local/include/QtCore/qnumeric.h \
		/usr/local/include/QtCore/qversiontagging.h \
		/usr/local/include/QtGui/qtgui-config.h \
		/usr/local/include/QtGui/qwindowdefs.h \
		/usr/local/include/QtCore/qobjectdefs.h \
		/usr/local/include/QtCore/qnamespace.h \
		/usr/local/include/QtCore/qobjectdefs_impl.h \
		/usr/local/include/QtGui/qwindowdefs_win.h \
		/usr/local/include/QtGui/qregion.h \
		/usr/local/include/QtCore/qrect.h \
		/usr/local/include/QtCore/qmargins.h \
		/usr/local/include/QtCore/qsize.h \
		/usr/local/include/QtCore/qpoint.h \
		/usr/local/include/QtCore/qdatastream.h \
		/usr/local/include/QtCore/qscopedpointer.h \
		/usr/local/include/QtCore/qiodevice.h \
		/usr/local/include/QtCore/qobject.h \
		/usr/local/include/QtCore/qstring.h \
		/usr/local/include/QtCore/qchar.h \
		/usr/local/include/QtCore/qbytearray.h \
		/usr/local/include/QtCore/qrefcount.h \
		/usr/local/include/QtCore/qarraydata.h \
		/usr/local/include/QtCore/qstringliteral.h \
		/usr/local/include/QtCore/qstringalgorithms.h \
		/usr/local/include/QtCore/qstringview.h \
		/usr/local/include/QtCore/qstringbuilder.h \
		/usr/local/include/QtCore/qlist.h \
		/usr/local/include/QtCore/qalgorithms.h \
		/usr/local/include/QtCore/qiterator.h \
		/usr/local/include/QtCore/qhashfunctions.h \
		/usr/local/include/QtCore/qpair.h \
		/usr/local/include/QtCore/qvector.h \
		/usr/local/include/QtCore/qcontainertools_impl.h \
		/usr/local/include/QtCore/qbytearraylist.h \
		/usr/local/include/QtCore/qstringlist.h \
		/usr/local/include/QtCore/qregexp.h \
		/usr/local/include/QtCore/qstringmatcher.h \
		/usr/local/include/QtCore/qcoreevent.h \
		/usr/local/include/QtCore/qmetatype.h \
		/usr/local/include/QtCore/qvarlengtharray.h \
		/usr/local/include/QtCore/qcontainerfwd.h \
		/usr/local/include/QtCore/qobject_impl.h \
		/usr/local/include/QtGui/qkeysequence.h \
		/usr/local/include/QtCore/qvariant.h \
		/usr/local/include/QtCore/qmap.h \
		/usr/local/include/QtCore/qdebug.h \
		/usr/local/include/QtCore/qhash.h \
		/usr/local/include/QtCore/qtextstream.h \
		/usr/local/include/QtCore/qlocale.h \
		/usr/local/include/QtCore/qshareddata.h \
		/usr/local/include/QtCore/qset.h \
		/usr/local/include/QtCore/qcontiguouscache.h \
		/usr/local/include/QtCore/qsharedpointer.h \
		/usr/local/include/QtCore/qsharedpointer_impl.h \
		/usr/local/include/QtCore/qurl.h \
		/usr/local/include/QtCore/qurlquery.h \
		/usr/local/include/QtCore/qfile.h \
		/usr/local/include/QtCore/qfiledevice.h \
		/usr/local/include/QtGui/qvector2d.h \
		/usr/local/include/QtGui/qtouchdevice.h \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		/usr/local/include/QtCore/qcoreapplication.h \
		/usr/local/include/QtCore/qeventloop.h \
		/usr/local/include/QtGui/qinputmethod.h \
		include/NGLScene.h \
		/Users/georgie/NGL/include/ngl/Vec3.h \
		/Users/georgie/NGL/include/ngl/Types.h \
		/Users/georgie/NGL/gl3w/gl3w.h \
		/Users/georgie/NGL/gl3w/glcorearb.h \
		/Users/georgie/NGL/include/ngl/fmt/format.h \
		/Users/georgie/NGL/include/ngl/fmt/format.cc \
		/Users/georgie/NGL/include/ngl/NGLMessage.h \
		/Users/georgie/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/ext/vector_bool3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/qualifier.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/simd/platform.h \
		/usr/local/include/glm/simd/neon.h \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/detail/compute_vector_relational.hpp \
		/usr/local/include/glm/ext/vector_bool3_precision.hpp \
		/usr/local/include/glm/ext/vector_float3.hpp \
		/usr/local/include/glm/ext/vector_float3_precision.hpp \
		/usr/local/include/glm/ext/vector_double3.hpp \
		/usr/local/include/glm/ext/vector_double3_precision.hpp \
		/usr/local/include/glm/ext/vector_int3.hpp \
		/usr/local/include/glm/ext/vector_int3_sized.hpp \
		/usr/local/include/glm/ext/scalar_int_sized.hpp \
		/usr/local/include/glm/ext/vector_uint3.hpp \
		/usr/local/include/glm/ext/vector_uint3_sized.hpp \
		/usr/local/include/glm/ext/scalar_uint_sized.hpp \
		include/WindowParams.h \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		/usr/local/include/QtGui/QPaintDeviceWindow \
		/usr/local/include/QtGui/qpaintdevicewindow.h \
		/usr/local/include/QtGui/QWindow \
		/usr/local/include/QtGui/qwindow.h \
		/usr/local/include/QtCore/QObject \
		/usr/local/include/QtCore/QEvent \
		/usr/local/include/QtCore/QMargins \
		/usr/local/include/QtCore/QRect \
		/usr/local/include/QtGui/qsurface.h \
		/usr/local/include/QtGui/qsurfaceformat.h \
		/usr/local/include/QtGui/qicon.h \
		/usr/local/include/QtGui/qpixmap.h \
		/usr/local/include/QtGui/qpaintdevice.h \
		/usr/local/include/QtGui/qcolor.h \
		/usr/local/include/QtGui/qrgb.h \
		/usr/local/include/QtGui/qrgba64.h \
		/usr/local/include/QtGui/qimage.h \
		/usr/local/include/QtGui/qpixelformat.h \
		/usr/local/include/QtGui/qtransform.h \
		/usr/local/include/QtGui/qmatrix.h \
		/usr/local/include/QtGui/qpolygon.h \
		/usr/local/include/QtCore/qline.h \
		/usr/local/include/QtGui/qcursor.h \
		/usr/local/include/QtGui/QPaintDevice \
		/usr/local/include/QtGui/QOpenGLContext \
		/usr/local/include/QtGui/qopenglcontext.h \
		/usr/local/include/QtCore/QScopedPointer \
		/usr/local/include/QtGui/QSurfaceFormat \
		/usr/local/include/QtGui/qopengl.h \
		/usr/local/include/QtCore/qt_windows.h \
		/usr/local/include/QtGui/qopengles2ext.h \
		/usr/local/include/QtGui/qopenglext.h \
		/usr/local/include/QtGui/qopenglversionfunctions.h \
		/usr/local/include/QtGui/QImage \
		/Users/georgie/NGL/include/ngl/ShaderLib.h \
		/Users/georgie/NGL/include/ngl/Shader.h \
		/Users/georgie/NGL/include/ngl/ShaderProgram.h \
		/Users/georgie/NGL/include/ngl/Util.h \
		/Users/georgie/NGL/include/ngl/Vec4.h \
		/Users/georgie/NGL/include/ngl/Vec2.h \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/ext/vector_bool2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		/usr/local/include/glm/ext/vector_bool2_precision.hpp \
		/usr/local/include/glm/ext/vector_float2.hpp \
		/usr/local/include/glm/ext/vector_float2_precision.hpp \
		/usr/local/include/glm/ext/vector_double2.hpp \
		/usr/local/include/glm/ext/vector_double2_precision.hpp \
		/usr/local/include/glm/ext/vector_int2.hpp \
		/usr/local/include/glm/ext/vector_int2_sized.hpp \
		/usr/local/include/glm/ext/vector_uint2.hpp \
		/usr/local/include/glm/ext/vector_uint2_sized.hpp \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/ext/vector_bool4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/detail/type_vec4_simd.inl \
		/usr/local/include/glm/ext/vector_bool4_precision.hpp \
		/usr/local/include/glm/ext/vector_float4.hpp \
		/usr/local/include/glm/ext/vector_float4_precision.hpp \
		/usr/local/include/glm/ext/vector_double4.hpp \
		/usr/local/include/glm/ext/vector_double4_precision.hpp \
		/usr/local/include/glm/ext/vector_int4.hpp \
		/usr/local/include/glm/ext/vector_int4_sized.hpp \
		/usr/local/include/glm/ext/vector_uint4.hpp \
		/usr/local/include/glm/ext/vector_uint4_sized.hpp \
		/Users/georgie/NGL/include/ngl/Mat2.h \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/ext/matrix_double2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/ext/matrix_double2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/ext/matrix_double2x3_precision.hpp \
		/usr/local/include/glm/ext/matrix_float2x3.hpp \
		/usr/local/include/glm/ext/matrix_float2x3_precision.hpp \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/ext/matrix_double2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/ext/matrix_double2x4_precision.hpp \
		/usr/local/include/glm/ext/matrix_float2x4.hpp \
		/usr/local/include/glm/ext/matrix_float2x4_precision.hpp \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/ext/matrix_double3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/ext/matrix_double3x2_precision.hpp \
		/usr/local/include/glm/ext/matrix_float3x2.hpp \
		/usr/local/include/glm/ext/matrix_float3x2_precision.hpp \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/ext/matrix_double3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/ext/matrix_double3x3_precision.hpp \
		/usr/local/include/glm/ext/matrix_float3x3.hpp \
		/usr/local/include/glm/ext/matrix_float3x3_precision.hpp \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/ext/matrix_double3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/ext/matrix_double3x4_precision.hpp \
		/usr/local/include/glm/ext/matrix_float3x4.hpp \
		/usr/local/include/glm/ext/matrix_float3x4_precision.hpp \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/ext/matrix_double4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/ext/matrix_double4x2_precision.hpp \
		/usr/local/include/glm/ext/matrix_float4x2.hpp \
		/usr/local/include/glm/ext/matrix_float4x2_precision.hpp \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/ext/matrix_double4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/ext/matrix_double4x3_precision.hpp \
		/usr/local/include/glm/ext/matrix_float4x3.hpp \
		/usr/local/include/glm/ext/matrix_float4x3_precision.hpp \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/ext/matrix_double4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		/usr/local/include/glm/detail/type_mat4x4_simd.inl \
		/usr/local/include/glm/ext/matrix_double4x4_precision.hpp \
		/usr/local/include/glm/ext/matrix_float4x4.hpp \
		/usr/local/include/glm/ext/matrix_float4x4_precision.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/detail/func_vector_relational_simd.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/func_exponential_simd.inl \
		/usr/local/include/glm/simd/exponential.h \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/detail/compute_common.hpp \
		/usr/local/include/glm/detail/func_common_simd.inl \
		/usr/local/include/glm/simd/common.h \
		/usr/local/include/glm/detail/func_geometric_simd.inl \
		/usr/local/include/glm/simd/geometric.h \
		/usr/local/include/glm/detail/func_matrix_simd.inl \
		/usr/local/include/glm/simd/matrix.h \
		/usr/local/include/glm/ext/matrix_double2x2_precision.hpp \
		/usr/local/include/glm/ext/matrix_float2x2.hpp \
		/usr/local/include/glm/ext/matrix_float2x2_precision.hpp \
		/Users/georgie/NGL/include/ngl/Mat3.h \
		/Users/georgie/NGL/include/ngl/Mat4.h \
		/Users/georgie/NGL/include/ngl/Singleton.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/func_trigonometric_simd.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/detail/func_packing_simd.inl \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl \
		/usr/local/include/glm/detail/func_integer_simd.inl \
		/usr/local/include/glm/simd/integer.h \
		/Users/georgie/NGL/include/ngl/NGLStream.h \
		/Users/georgie/NGL/include/ngl/NGLInit.h \
		/Users/georgie/NGL/include/ngl/VAOPrimitives.h \
		/Users/georgie/NGL/include/ngl/AbstractVAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/NGLSceneMouseControls.o: src/NGLSceneMouseControls.cpp include/NGLScene.h \
		/Users/georgie/NGL/include/ngl/Vec3.h \
		/Users/georgie/NGL/include/ngl/Types.h \
		/Users/georgie/NGL/gl3w/gl3w.h \
		/Users/georgie/NGL/gl3w/glcorearb.h \
		/Users/georgie/NGL/include/ngl/fmt/format.h \
		/Users/georgie/NGL/include/ngl/fmt/format.cc \
		/Users/georgie/NGL/include/ngl/NGLMessage.h \
		/Users/georgie/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/ext/vector_bool3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/qualifier.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/simd/platform.h \
		/usr/local/include/glm/simd/neon.h \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/detail/compute_vector_relational.hpp \
		/usr/local/include/glm/ext/vector_bool3_precision.hpp \
		/usr/local/include/glm/ext/vector_float3.hpp \
		/usr/local/include/glm/ext/vector_float3_precision.hpp \
		/usr/local/include/glm/ext/vector_double3.hpp \
		/usr/local/include/glm/ext/vector_double3_precision.hpp \
		/usr/local/include/glm/ext/vector_int3.hpp \
		/usr/local/include/glm/ext/vector_int3_sized.hpp \
		/usr/local/include/glm/ext/scalar_int_sized.hpp \
		/usr/local/include/glm/ext/vector_uint3.hpp \
		/usr/local/include/glm/ext/vector_uint3_sized.hpp \
		/usr/local/include/glm/ext/scalar_uint_sized.hpp \
		include/WindowParams.h \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		/usr/local/include/QtGui/qtguiglobal.h \
		/usr/local/include/QtCore/qglobal.h \
		/usr/local/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/QtCore/qconfig.h \
		/usr/local/include/QtCore/qtcore-config.h \
		/usr/local/include/QtCore/qsystemdetection.h \
		/usr/local/include/QtCore/qprocessordetection.h \
		/usr/local/include/QtCore/qcompilerdetection.h \
		/usr/local/include/QtCore/qtypeinfo.h \
		/usr/local/include/QtCore/qsysinfo.h \
		/usr/local/include/QtCore/qlogging.h \
		/usr/local/include/QtCore/qflags.h \
		/usr/local/include/QtCore/qatomic.h \
		/usr/local/include/QtCore/qbasicatomic.h \
		/usr/local/include/QtCore/qatomic_bootstrap.h \
		/usr/local/include/QtCore/qgenericatomic.h \
		/usr/local/include/QtCore/qatomic_cxx11.h \
		/usr/local/include/QtCore/qatomic_msvc.h \
		/usr/local/include/QtCore/qglobalstatic.h \
		/usr/local/include/QtCore/qmutex.h \
		/usr/local/include/QtCore/qnumeric.h \
		/usr/local/include/QtCore/qversiontagging.h \
		/usr/local/include/QtGui/qtgui-config.h \
		/usr/local/include/QtGui/QPaintDeviceWindow \
		/usr/local/include/QtGui/qpaintdevicewindow.h \
		/usr/local/include/QtGui/QWindow \
		/usr/local/include/QtGui/qwindow.h \
		/usr/local/include/QtCore/QObject \
		/usr/local/include/QtCore/qobject.h \
		/usr/local/include/QtCore/qobjectdefs.h \
		/usr/local/include/QtCore/qnamespace.h \
		/usr/local/include/QtCore/qobjectdefs_impl.h \
		/usr/local/include/QtCore/qstring.h \
		/usr/local/include/QtCore/qchar.h \
		/usr/local/include/QtCore/qbytearray.h \
		/usr/local/include/QtCore/qrefcount.h \
		/usr/local/include/QtCore/qarraydata.h \
		/usr/local/include/QtCore/qstringliteral.h \
		/usr/local/include/QtCore/qstringalgorithms.h \
		/usr/local/include/QtCore/qstringview.h \
		/usr/local/include/QtCore/qstringbuilder.h \
		/usr/local/include/QtCore/qlist.h \
		/usr/local/include/QtCore/qalgorithms.h \
		/usr/local/include/QtCore/qiterator.h \
		/usr/local/include/QtCore/qhashfunctions.h \
		/usr/local/include/QtCore/qpair.h \
		/usr/local/include/QtCore/qvector.h \
		/usr/local/include/QtCore/qcontainertools_impl.h \
		/usr/local/include/QtCore/qpoint.h \
		/usr/local/include/QtCore/qbytearraylist.h \
		/usr/local/include/QtCore/qstringlist.h \
		/usr/local/include/QtCore/qregexp.h \
		/usr/local/include/QtCore/qstringmatcher.h \
		/usr/local/include/QtCore/qcoreevent.h \
		/usr/local/include/QtCore/qscopedpointer.h \
		/usr/local/include/QtCore/qmetatype.h \
		/usr/local/include/QtCore/qvarlengtharray.h \
		/usr/local/include/QtCore/qcontainerfwd.h \
		/usr/local/include/QtCore/qobject_impl.h \
		/usr/local/include/QtCore/QEvent \
		/usr/local/include/QtCore/QMargins \
		/usr/local/include/QtCore/qmargins.h \
		/usr/local/include/QtCore/QRect \
		/usr/local/include/QtCore/qrect.h \
		/usr/local/include/QtCore/qsize.h \
		/usr/local/include/QtGui/qsurface.h \
		/usr/local/include/QtGui/qsurfaceformat.h \
		/usr/local/include/QtGui/qwindowdefs.h \
		/usr/local/include/QtGui/qwindowdefs_win.h \
		/usr/local/include/QtGui/qicon.h \
		/usr/local/include/QtGui/qpixmap.h \
		/usr/local/include/QtGui/qpaintdevice.h \
		/usr/local/include/QtGui/qcolor.h \
		/usr/local/include/QtGui/qrgb.h \
		/usr/local/include/QtGui/qrgba64.h \
		/usr/local/include/QtCore/qsharedpointer.h \
		/usr/local/include/QtCore/qshareddata.h \
		/usr/local/include/QtCore/qhash.h \
		/usr/local/include/QtCore/qsharedpointer_impl.h \
		/usr/local/include/QtGui/qimage.h \
		/usr/local/include/QtGui/qpixelformat.h \
		/usr/local/include/QtGui/qtransform.h \
		/usr/local/include/QtGui/qmatrix.h \
		/usr/local/include/QtGui/qpolygon.h \
		/usr/local/include/QtGui/qregion.h \
		/usr/local/include/QtCore/qdatastream.h \
		/usr/local/include/QtCore/qiodevice.h \
		/usr/local/include/QtCore/qline.h \
		/usr/local/include/QtGui/qcursor.h \
		/usr/local/include/QtGui/QPaintDevice \
		/usr/local/include/QtGui/QOpenGLContext \
		/usr/local/include/QtGui/qopenglcontext.h \
		/usr/local/include/QtCore/QScopedPointer \
		/usr/local/include/QtGui/QSurfaceFormat \
		/usr/local/include/QtGui/qopengl.h \
		/usr/local/include/QtCore/qt_windows.h \
		/usr/local/include/QtGui/qopengles2ext.h \
		/usr/local/include/QtGui/qopenglext.h \
		/usr/local/include/QtGui/qopenglversionfunctions.h \
		/usr/local/include/QtCore/qvariant.h \
		/usr/local/include/QtCore/qmap.h \
		/usr/local/include/QtCore/qdebug.h \
		/usr/local/include/QtCore/qtextstream.h \
		/usr/local/include/QtCore/qlocale.h \
		/usr/local/include/QtCore/qset.h \
		/usr/local/include/QtCore/qcontiguouscache.h \
		/usr/local/include/QtGui/QImage \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/georgie/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/include/QtGui/qkeysequence.h \
		/usr/local/include/QtCore/qurl.h \
		/usr/local/include/QtCore/qurlquery.h \
		/usr/local/include/QtCore/qfile.h \
		/usr/local/include/QtCore/qfiledevice.h \
		/usr/local/include/QtGui/qvector2d.h \
		/usr/local/include/QtGui/qtouchdevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLSceneMouseControls.o src/NGLSceneMouseControls.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

